export default[
{"id":1,"projectName":"Project Name","website":"www.website.com","date":"12-12-2018","clientName":"Client Name","issues":'Issues - 64', "status": "in progress"},
{"id":2,"projectName":"Project Name","website":"www.website.com","date":"12-12-2018","clientName":"Client Name","issues":'Issues - 64', "status": "new"},
{"id":3,"projectName":"Project Name","website":"www.website.com","date":"12-12-2018","clientName":"Client Name","issues":'Issues - 64', "status": "new"},
{"id":4,"projectName":"Project Name","website":"www.website.com","date":"12-12-2018","clientName":"Client Name","issues":'Issues - 64', "status": "done"},
{"id":5,"projectName":"Project Name","website":"www.website.com","date":"12-12-2018","clientName":"Client Name","issues":'Issues - 64', "status": "new"},
{"id":6,"projectName":"Project Name","website":"www.website.com","date":"12-12-2018","clientName":"Client Name","issues":'Issues - 64', "status": "in progress"},
{"id":7,"projectName":"Project Name","website":"www.website.com","date":"12-12-2018","clientName":"Client Name","issues":'Issues - 64', "status": "new"},
{"id":8,"projectName":"Project Name","website":"www.website.com","date":"12-12-2018","clientName":"Client Name","issues":'Issues - 64', "status": "done"},
{"id":9,"projectName":"Project Name","website":"www.website.com","date":"12-12-2018","clientName":"Client Name","issues":'Issues - 64', "status": "new"},
{"id":10,"projectName":"Project Name","website":"www.website.com","date":"12-12-2018","clientName":"Client Name","issues":'Issues - 64', "status": "new"},
{"id":11,"projectName":"Project Name","website":"www.website.com","date":"12-12-2018","clientName":"Client Name","issues":'Issues - 64', "status": "in progress"},
{"id":12,"projectName":"Project Name","website":"www.website.com","date":"12-12-2018","clientName":"Client Name","issues":'Issues - 64', "status": "done"},
{"id":13,"projectName":"Project Name","website":"www.website.com","date":"12-12-2018","clientName":"Client Name","issues":'Issues - 64', "status": "new"},
{"id":14,"projectName":"Project Name","website":"www.website.com","date":"12-12-2018","clientName":"Client Name","issues":'Issues - 64', "status": "done"},
{"id":15,"projectName":"Project Name","website":"www.website.com","date":"12-12-2018","clientName":"Client Name","issues":'Issues - 64', "status": "in progress"},
{"id":16,"projectName":"Project Name","website":"www.website.com","date":"12-12-2018","clientName":"Client Name","issues":'Issues - 64', "status": "new"},
{"id":17,"projectName":"Project Name","website":"www.website.com","date":"12-12-2018","clientName":"Client Name","issues":'Issues - 64', "status": "new"},
{"id":18,"projectName":"Project Name","website":"www.website.com","date":"12-12-2018","clientName":"Client Name","issues":'Issues - 64', "status": "new"},
{"id":19,"projectName":"Project Name","website":"www.website.com","date":"12-11-2018","clientName":"Client Name","issues":'Issues - 64', "status": "done"},
{"id":20,"projectName":"Project Name","website":"www.website.com","date":"12-12-2019","clientName":"Client Name","issues":'Issues - 64', "status": "in progress"}
]